[build]
publish = "frontend"
command = ""          # sitio puramente estático

[[redirects]]
  from   = "/api/*"
  to     = "https://appgym-production-64ac.up.railway.app/:splat"
  status = 200
  force  = true
